CREATE TABLE `game_rating` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `GAMEPLAY` decimal(4,2) NOT NULL,
  `GRAPHICS` decimal(4,2) NOT NULL,
  `DIFFICULTY` decimal(4,2) NOT NULL,
  `PERFORMANCE` decimal(4,2) NOT NULL,
  `STORY` decimal(4,2) DEFAULT NULL,
  `SOUND` decimal(4,2) NOT NULL,
  `IMMERSION` decimal(4,2) NOT NULL,
  `MATCH_MAKING` decimal(4,2) DEFAULT NULL,
  `COMPETITIVE_BALANCE` decimal(4,2) DEFAULT NULL,
  `COOP` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;