CREATE TABLE `game` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `STORY_MODE_STATUS` varchar(255) NOT NULL,
  `MULTIPLAYER_STATUS` varchar(255) NOT NULL,
  `ACHIEVEMENTS_STATUS` varchar(255) NOT NULL,
  `FINISH_DATE` date DEFAULT NULL,
  `ONE_HUNDRED_PERCENT_DATE` date DEFAULT NULL,
  `ALL_ACHIEVEMENTS_DATE` date DEFAULT NULL,
  `LAUNCHER` varchar(255) NOT NULL,
  `TOTAL_RATING` decimal(10,2) DEFAULT NULL,
  `GAME_RATING` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GAME_RATING` (`GAME_RATING`),
  CONSTRAINT `FK_GAME_RATING` FOREIGN KEY (`GAME_RATING`) REFERENCES `game_rating` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;