CREATE TABLE game_collection_relationship (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GAME_ID BIGINT NOT NULL,
    GAME_COLLECTION_ID BIGINT NOT NULL,
    CONSTRAINT fk_game FOREIGN KEY (GAME_ID) REFERENCES game(id),
    CONSTRAINT fk_game_collection FOREIGN KEY (GAME_COLLECTION_ID) REFERENCES game_collection(id)
);